### ISSUE TITLE
Useability issues

### ISSUE THREAD

**Issue by jjsnaretto** [microsoft/wiql-editor#26]
**Describe the bug**
When editing a query:
- The new dialogue is small and hard to read, as opposed to how it was before filling the whole screen.
- The new dialogue doesn't use the full height of the screen.
Extension:
- The new extension only works with the new boards, which is not good yet. The old extension, for some reason, got removed from the Marketplace and DevOps automatically.

**Environment:**
 - Browser Edge
 - Azure DevOps Server

**To Reproduce**
Steps to reproduce the behaviour:
- Just edit a query.

**Expected behaviour**
- A good user experience as it worked before, or at least a way to configure it.

**Comment by AminTi** [comment]
Thank you for bringing this to our attention. I will investigate the issue further and update you accordingly after testing.

**Comment by AminTi** [comment]
Hi, we have noticed your feedback and are continuously developing this extension. Let us know if you need any assistance
