### ISSUE TITLE
Dark mode compatibility

### ISSUE THREAD

**Issue by BarrieSharp** [microsoft/wiql-editor#27]
**Describe the bug**
Some elements are difficult to read in dark mode.

**Environment:**
 - edge
 - hosted (Azure Devops)

**Screenshots**
![image](https://github.com/microsoft/wiql-editor/assets/11975682/bd353147-f645-4245-bb77-d1146dbf988a)
![image](https://github.com/microsoft/wiql-editor/assets/11975682/5886ced7-c958-4569-8759-e3faad53d263)

**To Reproduce**
Use the playground or editor.

**Expected behavior**
Adapt the colour scheme to be more legible in dark mode.

**Comment by AminTi** [comment]
This issue has been resolved; the background of the Monaco editor will remain white
![Uploading Screenshot 2024-05-02 at 11.12.27.png…]()
