### ISSUE TITLE
Editor UX

### ISSUE THREAD

**Issue by BarrieSharp** [microsoft/wiql-editor#28]
**Describe the bug**
When using a previous version from [Otto Streifel] (https://github.com/ostreifel), you could use 'IntelliSense'/auto-complete in the editor when pressing Ctrl+Space which was valuable for discovering the correct syntax/names. It also showed a path in the results indicating hierarchy in results.

As a nice to have, the Editor/Result divider could be adjustable so that the more of the query was visible when editing. Maybe a side-by-side option would make better use of a wide screen.

**Environment:**
 - edge
 - hosted (Azure Devops)

**To Reproduce**
For looking at hierarchy:
SELECT
        [System.Id],
        [System.WorkItemType],
        [System.Title],
        [System.AssignedTo],
        [System.State],
        [System.Tags],
        [System.AreaPath],
        [System.IterationPath]
FROM workitemLinks
WHERE
        (
                [Source].[System.TeamProject] = @project
                AND [Source].[System.WorkItemType] <> ''
        )
        AND (
                [System.Links.LinkType] = 'System.LinkTypes.Hierarchy-Forward'
        )
        AND (
                [Target].[System.TeamProject] = @project
                AND [Target].[System.WorkItemType] <> ''
                AND [Target].[System.State] <> 'Closed'
                AND [Target].[System.State] <> 'Removed'
        )
ORDER BY [System.WorkItemType],
        [System.State],
        [System.Id]
MODE (Recursive)

**Expected behavior**
'IntelliSense'/auto-complete should be active in the editor giving suggestions.

Editor layout could be more flexible.

**Comment by MOlausson** [comment]
@BarrieSharp thanks for reporting, this sounds like something that should work.
