### ISSUE TITLE
Not/partially working at Azuredevops Server 2022

### ISSUE THREAD

**Issue by softwarekontorlizenzen** [microsoft/wiql-editor#31]
**Describe the bug**
Can't open/edit querries in/as WIQL after installation of WIQL Editor

**Environment:**
 - Browser Edge
 - Azure DevOps Server 2022.0.1 (AzureDevOpsServer_20231109.3)

**Screenshots**
![Screenshot 2024-03-22 080217](https://github.com/microsoft/wiql-editor/assets/158072716/3ac9d136-1f1e-48f2-b8c5-d2d75f83e967)
![Screenshot 2024-03-22 080218](https://github.com/microsoft/wiql-editor/assets/158072716/c79df351-c513-47d3-b25e-9944b167c160)

**To Reproduce**
1. Go to Querries
2. Click on a query
3. Try to open it in WIQL

**Expected behavior**
Show selected query in WIQL

**Comment by AminTi** [comment]
Thank you for bringing this to our attention. We will conduct testing and provide you with an update.

**Comment by allankichowdary** [comment]
Same issue here too. we installed recently and not able to see option for selection.

**Comment by AminTi** [comment]
Hi everyone, I've just tested a workaround, and it appears that you still have the capability to open and edit a query. We'll review it again and provide an update shortly.
<img width="991" alt="Screenshot 2024-04-04 at 16 55 37" src="http
<img width="991" alt="Screenshot 2024-04-04 at 16 55 37" src="https://github.com/microsoft/wiql-editor/assets/54841342/ad143c89-71c1-4f96-a519-8252873ab1af">
s://github.com/microsoft/wiql-editor/assets/54841342/d9668e3a-6d56-4af7-8d4d-d57e4bccb12c">

**Comment by AminTi** [comment]
<img width="1336" alt="Screenshot 2024-04-04 at 16 56 15" src="https://github.com/microsoft/wiql-editor/assets/54841342/b88cf369-9f24-4626-a5a9-9fbf938dae8e">

**Comment by JohanSpannare** [comment]
@AminTi  Any updates on this, is it confirmed that there is a bug? and if so, when can you expect a patch been released?

**Comment by AminTi** [comment]
Hi, the issue is related to the Old board hub and on-premises Azure DevOps environment. I've already submitted a report detailing the problem.

**Comment by JohanSpannare** [comment]
@AminTi  do you have any link to the report details? 

We are planing on installing it on an 2022.1 Onprem installation, that is why i wonder if the bug is still precent.

**Comment by AminTi** [comment]
The extension isn't broken; you can edit the query in other views, and all other functions work as expected.

**Comment by AminTi** [comment]
The extension isn't broken ; you can edit the query in other views, and all other functions work as expected in 2022 onprem
<img width="1203" alt="Screenshot 2024-04-25 at 19 15 26" src="https://github.com/microsoft/wiql-editor/assets/54841342/bbfb6344-0dac-4a13-b512-3533d7972473">
if you click there, you will be able to edit the query.
