### ISSUE TITLE
Saving not working

### ISSUE THREAD

**Issue by bergamin** [microsoft/wiql-editor#38]
**Describe the bug**
When hitting "Save Query" button, the query isn't saved. An error happens that is only visible in the console and no UI indication is made

**Environment:**
 - Browser: Vivaldi
 - Hosted Azure DevOps

**Screenshots**
![image](https://github.com/microsoft/wiql-editor/assets/14339291/e26bc1d6-933f-4c0e-a945-2b8d75319e75)

The query that's being edited:
```sql
SELECT
    [System.Id],
    [System.WorkItemType],
    [System.Title],
    [System.State],
    [System.AreaPath],
    [System.IterationPath],
    [Microsoft.VSTS.Scheduling.CompletedWork],
    [Microsoft.VSTS.Scheduling.RemainingWork],
    [Microsoft.VSTS.Common.ResolvedDate],
    [Microsoft.VSTS.Common.ClosedDate],
    [System.Tags]
FROM workitems
WHERE
    [System.AssignedTo] = @me
    AND (
        [Microsoft.VSTS.Common.ClosedDate] >= @startOfDay('-6d') -- This function seems to puzzle the editor. It clearly works, but it underlines it in red. That's going to be a separate report, but just to add that this isn't the cause of the error, as it also happens in a query that doesn't have it
        OR [System.State] <> 'Closed'
    )
ORDER BY [Microsoft.VSTS.Common.ClosedDate] DESC,
    [System.IterationPath] DESC,
    [System.AreaPath],
    [System.Id] DESC -- This is the new line being added to the query
```

**To Reproduce**
1. Go to Wiql editor
2. Edit the Wiql
3. Save query
4. Nothing happens

**Expected behavior**
It to save the query

**Additional context**
It's been some time since I created this query. Before the new boards thing that broke a lot of stuff, so perhaps this issue is yet another bug caused by the new boards experience

**Comment by joestanco** [comment]
Would love to see this get fixed!

**Comment by MuminElsayed** [comment]
Issue still persists, trying to save anything in the wiql editor pops the exact same error. Using Firefox 129.0.2.

**Comment by RasdaGit** [comment]
Same issue across my organization. This is a big problem. Pleace fix :)

**Comment by jeremiahenkelitvt** [comment]
Hi, this issues is also in my organization. Can we get it fixed?

**Comment by jeremiahenkelitvt** [comment]
@AminTi Could you give us an update if this is being worked on?

**Comment by RasdaGit** [comment]
I have made a report directly to Microsoft regarding this issue.
Please upvote it and tell your colleagues.

https://developercommunity.visualstudio.com/t/Wiql-editor-cannot-save-and-no-error-is/10771191?stateGroup=active

**Comment by jeremiahenkelitvt** [comment]
@RasdaGit @bergamin @MuminElsayed @joestanco  The Problem for us was that we were still using the WIQL Editor Extension by Otto Streifel, but this extension is now outdated and a new extension by microsoft DevLabs was published.

Remove the old extension and then add the new one to your orgs

**Comment by AminTi** [comment]
Hi everyone, please uninstall the old extension by Otto and install the new one by Microsoft DevLabs.

**Comment by AminTi** [comment]
II will close this issue. If you still experience the same problem, please create a new issue.
