### ISSUE TITLE
Issue reporting link follows the wrong repository

### ISSUE THREAD

**Issue by bergamin** [microsoft/wiql-editor#39]
**Describe the bug**
The link follows the original repository instead of this one. At least, the owner of the original repo archived the repo today and added a pinned issue pointing to this place after I asked them about the repo status, so this isn't going to be a big issue anymore

**Environment:**
 - Browser: Vivaldi
 - Hosted Azure DevOps

**Screenshots**
![image](https://github.com/microsoft/wiql-editor/assets/14339291/e35aad93-2244-4f32-8016-7630732c7bac)
![image](https://github.com/microsoft/wiql-editor/assets/14339291/b763c2f2-512a-4c66-827c-385d29957ac8)

**To Reproduce**
1. Open editor
2. Click on Report an issue

**Expected behavior**
It to send people here

**Comment by AminTi** [comment]
Hi, The link is correct, and you should use this extension instead for Otto's extension

**Comment by bergamin** [comment]
@AminTi, thanks. I'll report it to the people who manages our Azure DevOps.

Is it possible to migrate without losing our queries?
